import "./globals.css";

import localFont from "next/font/local";

import ClientLayoutPage from "./client-layout";

import { Toaster } from "react-hot-toast";
import { cookies } from "next/headers";

const telegraf = localFont({
    src: [
        {
            path: "./fonts/telegraf-regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "./fonts/telegraf-medium.woff2",
            weight: "500",
            style: "italic",
        },
        {
            path: "./fonts/telegraf-semibold.woff2",
            weight: "600",
            style: "normal",
        },
        {
            path: "./fonts/telegraf-bold.woff2",
            weight: "700",
            style: "italic",
        },
    ],
});
export const revalidate = 0;

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const color = cookies().get("color");
    const theme = cookies().get("theme");

    return (
        <html lang="en" className={`${color?.value ?? "default"} ${theme?.value ?? "chill"}  `}>
            <body className={`${telegraf.className} scrollbar overflow-hidden ${theme?.value ?? "chill"} `}>
                {/* @ts-expect-error Server Component */}
                <ClientLayoutPage>{children}</ClientLayoutPage>
                <Toaster position="bottom-right" />
            </body>
        </html>
    );
}

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
